services:
  open-webui:
    # image: ghcr.io/open-webui/open-webui:v0.6.43
    image: ghcr.io/open-webui/open-webui:v0.11.1
    container_name: open-webui
    restart: unless-stopped

    ports:
      - "3000:8080"

    environment:
      ENABLE_OLLAMA_API: "true"
      OLLAMA_BASE_URL: "http://10.21.214.137:11434"

      # Force environment configuration to win over DB configuration
      ENABLE_PERSISTENT_CONFIG: "false"

      # Optional: make Open WebUI itself operate without Internet
      OFFLINE_MODE: "true"
      HF_HUB_OFFLINE: "1"

    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - ai-platform
volumes:
  open-webui-data:
    name: open-webui-data

networks:
  ai-platform:
    name: ai-platform
    external: true
